/*
    CREATE A TABLE

    CREATE TABLE table_name (
        col1 type_data,
        col2 type_data,
        ...
        PRIMARY KEY (col1, col2,...),
        FOREIGN KEY col3 REFERENCE table (col_in_table)
    );
*/

CREATE TABLE ot.persons(
    person_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY(person_id)
);

/*
    ALTER TABLE

    ALTER TABLE table_name action;
    The ALTER TABLE statement allows you to:
        Add one or more columns
        Modify column definition
        Drop one or more columns
        Rename columns
        Rename table
*/

ALTER TABLE table_name
ADD (
    column_name type constraint,
    column_name type constraint,
    ...
);

ALTER TABLE table_name
  MODIFY ( column_1 type constraint,
          column_1 type constraint,
         ...);

ALTER TABLE table_name 
DROP (column_1,column_2,...);

ALTER TABLE table_name
RENAME COLUMN column_name TO new_name;

ALTER TABLE table_name
RENAME TO new_table_name;


/*
    DROP TABLE

    DROP TABLE schema_name.table_name
    [CASCADE CONSTRAINTS | PURGE];

    In this statement:

First, indicate the table and its schema that you want to drop after the DROP TABLE clause.
If you don’t specify the schema name explicitly, the statement assumes that you are removing
 the table from your own schema.

Second, specify CASCADE CONSTRAINTS clause to remove all referential integrity constraints 
which refer to primary and unique keys in the table. In case such referential integrity constraints 
exist and you don’t use this clause, Oracle returns an error and stops removing the table.

Third, specify PURGE clause if you want to drop the table and release the space associated with 
it at once. By using the PURGE clause, Oracle will not place the table and its dependent objects 
into the recycle bin.

Notice that the PURGE clause does not allow you to roll back or recover the table that you dropped. 
Therefore, it is useful if you don’t want the sensitive data to appear in the recycle bin.
*/


